### ISSUE TITLE
change VersionRange comparison so 2.0-SNAPSHOT does not satisfy 2.0

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/gestalt#113]
We've decided to change version comparison to be more consistent with Semantic Versioning.

Currently a dependency declared as `2.0.0` may be satisfied by a module implementing `2.0.0-SNAPSHOT`. This should not be true under semantic versioning.

Requires a change to the VersionRange class and tests, as well as documentation. (Check both Terasology and gestalt wikis.)

**Comment by jdrueckert** [comment]
Closed by #115
