### ISSUE TITLE
Support resolving a particular module version

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/gestalt#33]
Currently, only module names can be used to resolve modules. When multiple versions of a module are available, it might be useful to resolve a particular version (or a range?) of a module.
For example, someone might want to play v0.9 even if v1.0 is already available.

The master-server uses a workaround based on a fake module to resolve a specified version of a module:

```java
ModuleMetadata meta = new ModuleMetadata();
Name fakeName = new Name("fake");
meta.setId(fakeName);
meta.setVersion(new Version(1, 0, 0));
DependencyInfo di = new DependencyInfo();
di.setId(name);
di.setMinVersion(version);
di.setMaxVersion(version.getNextPatchVersion());
meta.getDependencies().add(di);
DummyModule fakeMod = new DummyModule(meta);

moduleRegistry.add(fakeMod);
ResolutionResult result = dependencyResolver.resolve(fakeName);
moduleRegistry.remove(fakeMod);
```

I would find it useful if this was supported by DependencyResolver.

**Comment by immortius** [comment]
Essentially the ability to provide additional constraints to the resolution
process? Seems reasonable. You can also provide a module registry with
other versions removed.

It isn't immediately obvious to me why the master server cares about
modules at all, but that isn't relevant .
