### ISSUE TITLE
A way is needed to pass data to RegisterAssetDeltaFileFormat annotated classes

### ISSUE THREAD

**Issue by flo** [MovingBlocks/gestalt#35]
The class PrefabDeltaFormat in terasology is annotated with this annotation and is currently using a static way to get data (CoreRegistry). There should be a way to get data to RegisterAssetDeltaFileFormat classes.

The tricky part about adding dependency injection will be the documentation with javadoc: If the annotation is defined in gestal core it can't obviously explain how the dependency injection is done in terasology.

**Comment by immortius** [comment]
This has already been implemented: ModuleAwareAssetTypeManager has a constructor in which you can pass a [ClassFactory](https://github.com/MovingBlocks/gestalt/blob/develop/gestalt-util/src/main/java/org/terasology/util/reflection/ClassFactory.java), so you can substitute with a class factory that injects as desired. Additionally the [SimpleClassFactory](https://github.com/MovingBlocks/gestalt/blob/develop/gestalt-util/src/main/java/org/terasology/util/reflection/SimpleClassFactory.java) is set up to inject parameters into the constructor of a class.

It is also likely that the PrefabDeltaFormat shouldn't be injected by the annotation and instead manually registered as part of the engine lifecycle, but that is under review.

**Comment by flo** [comment]
Ok, so with that information I tried to register the `PrefabDeltaFormat` manully in `TerasologyEngine#initAssets` via:
```
assetTypeManager.registerCoreDeltaFormat(Prefab.class, new PrefabDeltaFormat(context));
```

However the `PrefabDeltaFormat` needs a instance of `ComponentLibrary` that gets added to the context in `ApplyModulesUtil.applyModules(context)` that gets called directly after `initAssets`.

I guess however that moving `initAssets` after `applyModules` is a bad idea. Any thoughts on that?

**Comment by immortius** [comment]
The adding of types/formats/etc has to happen before an environment switch (the environment switch applies them). Which would mean it has to happen in the middle of the applyModules() method at the moment - after the context is created and set up, and before the switch.

For now I suggest doing whatever works. I am working towards refactoring all this lifecycle shenanigans, so in the end the applyModules method won't be this weird hanger on doing several tasks.
